import { SemanticAST } from '../types';
import path from 'path';
import fs from 'fs/promises';

export class ReactCompiler {
  static async emit(ast: SemanticAST, targetDir: string): Promise<void> {
    const srcDir = path.join(targetDir, 'frontend', 'src');
    
    // In a real compiler, we would generate a full Vite + React app from the AST.
    // For this prototype, we'll write a semantic components map file.
    
    const componentsCode = ast.components.map(c => `
export function ${c.name}() {
  return (
    <div className="semantic-component" data-purpose="${c.purpose}">
      {/* Generated by ReactCompiler from SemanticAST */}
      <h2>${c.name}</h2>
    </div>
  );
}
`).join('\n');

    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'SemanticComponents.tsx'), componentsCode, 'utf-8');
    
    // Write out the AST itself for debugging/observability
    await fs.writeFile(path.join(targetDir, 'frontend', 'semantic-ast.json'), JSON.stringify(ast, null, 2), 'utf-8');
  }
}
